version: '2'
services:
  hitchhiker:
    image: brookshi/hitchhiker:v0.1.0
    container_name: hitchhiker
    environment:
      - HITCHHIKER_DB_HOST=hitchhiker-mysql
      - HITCHHIKER_APP_HOST=http://localhost:8080/ # should change in run time.
    ports:
      - "8080:8080"
    external_links:
      - hitchhiker-mysql:hitchhiker-mysql